// <auto-generated />
using ApiToDoList;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiToDoList.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20190809070716_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ApiToDoList.Models.Item", b =>
                {
                    b.Property<int>("TodoId");

                    b.Property<int>("ItemId");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("TodoId", "ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ApiToDoList.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ApiToDoList.Models.Item", b =>
                {
                    b.HasOne("ApiToDoList.Models.Todo", "Todo")
                        .WithMany("Items")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
