// <auto-generated />
using System;
using ApiToDoList;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiToDoList.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20190802152157_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ApiToDoList.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Objectif");

                    b.Property<int?>("TodoListID");

                    b.HasKey("ID");

                    b.HasIndex("TodoListID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ApiToDoList.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemTitle");

                    b.HasKey("ID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ApiToDoList.Models.Item", b =>
                {
                    b.HasOne("ApiToDoList.Models.Todo", "Todo")
                        .WithMany("Items")
                        .HasForeignKey("TodoListID");
                });
#pragma warning restore 612, 618
        }
    }
}
